"""Add level field to XSSComment

Revision ID: 552ad145c2d6
Revises: 88a1974567cf
Create Date: 2025-02-16 03:33:06.291852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552ad145c2d6'
down_revision: Union[str, None] = '88a1974567cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xss_comments', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xss_comments', 'level')
    # ### end Alembic commands ###
